<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>soccerline_icon.ico</ApplicationIcon>
    <AssemblyName>SoccerlineApp_v0.6</AssemblyName>
    <AssemblyVersion>0.6.0.0</AssemblyVersion>
    <FileVersion>0.6.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="soccerline_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>

</Project>
